apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    git: ssh://git@github.com/mark-eva/flux-lab-nginxhello-hr.yaml
    path: helm/chart
    ref: master
  rollback:
    enable: true
    retry: true
